class AddPublicationTypes < ActiveRecord::Migration
  def change
#    PublicationType.delete_all

p=PublicationType.new(publication_type_code: 'article', content_type: 'ref', form_template: 'article-ref')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'article', content_type: 'ovr', form_template: 'article-ref')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'article', content_type: 'for', form_template: 'article-ref')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'article', content_type: 'pop', form_template: 'article')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'article', content_type: 'rec', form_template: 'article')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'book', content_type: 'ref', form_template: 'book')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'book', content_type: 'nap', form_template: 'book')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'book, edited', content_type: 'ref', form_template: 'book-edited')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'book, edited', content_type: 'nap', form_template: 'book-edited')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'textbook', content_type: 'nap', form_template: 'book')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'report', content_type: 'nap', form_template: 'book')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'book chapter', content_type: 'ref', form_template: 'book-chapter')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'book chapter', content_type: 'nap', form_template: 'book-chapter')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'conference proceeding', content_type: 'ref', form_template: 'conference-proc')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'conference proceeding', content_type: 'abs', form_template: 'conference-proc')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'conference proceeding', content_type: 'pos', form_template: 'conference-proc')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'conference proceeding', content_type: 'nap', form_template: 'conference-proc')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'artistic work', content_type: 'ref', form_template: 'artistic-work')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'artistic work', content_type: 'nap', form_template: 'artistic-work')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'text critical edition', content_type: 'nap', form_template: 'text-critical-edition')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'doctoral thesis', content_type: 'nap', form_template: 'thesis')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'licentiate thesis', content_type: 'nap', form_template: 'thesis')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'patent', content_type: 'nap', form_template: 'patent')
p.save(:validate=>false)
p=PublicationType.new(publication_type_code: 'other', content_type: 'nap', form_template: 'other')
p.save(:validate=>false)

  end
end
